name: my_gallery
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  splash_screen_view: ^3.0.0
  carousel_slider: ^4.1.1
  lottie: ^1.2.2
  intl: ^0.17.0
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  percent_indicator: ^4.2.2
  smooth_page_indicator: ^1.0.0+2
  image_picker: ^0.8.5+3
  modal_progress_hud_nsn: ^0.3.0
  cached_network_image: ^3.2.2
  flutter_svg:
  http: ^0.13.5
  photo_view: ^0.14.0
  conditional_builder_null_safety: ^0.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/


#  fonts:
#    - family: IconBroken
#      fonts:
#        - asset: assets/icons/icons.ttf
